import type { SupplierProfile, SupplierReview } from '@/types';

export const MOCK_SUPPLIERS: SupplierProfile[] = [
  {
    id: 'sup-001',
    slug: 'swift-plumbing-birmingham',
    companyName: 'Swift Plumbing & Heating',
    ownerName: 'James Thornton',
    bio: 'Family-run plumbing and heating business serving Birmingham and the surrounding West Midlands for over 15 years. Gas Safe registered, fully insured. Specialising in boiler installations, bathroom refits and emergency call-outs.',
    trades: ['plumbers', 'gas-engineers'],
    coveragePostcodes: ['B1', 'B2', 'B3', 'B4', 'B5', 'B11', 'B12', 'B13', 'B14', 'B15', 'B16'],
    contact: {
      email: 'james@swiftplumbing.co.uk',
      phone: '0121 400 1234',
      website: 'https://swiftplumbing.co.uk',
      address: 'Edgbaston, Birmingham, B16',
    },
    verification: 'featured',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 84,
      averageRating: 4.9,
      jobsCompleted: 312,
      responseTimeHours: 2,
      memberSince: '2021-03-15',
    },
    pricing: {
      'boiler-service': { priceFrom: 7500, priceTo: 12000, leadCost: 200 },
      'boiler-installation': { priceFrom: 200000, priceTo: 350000, leadCost: 300 },
      'bathroom-refit': { priceFrom: 400000, priceTo: 800000, leadCost: 400 },
      'leak-repair': { priceFrom: 8000, priceTo: 25000, leadCost: 100 },
    },
    accountBalance: 5420,
  },
  {
    id: 'sup-002',
    slug: 'midland-electrical-services',
    companyName: 'Midland Electrical Services',
    ownerName: 'Sarah Patel',
    bio: 'NICEIC-accredited electrician team covering Coventry and greater Warwickshire. Specialising in rewires, consumer unit upgrades, EV charger installation and commercial fit-outs.',
    trades: ['electricians'],
    coveragePostcodes: ['CV1', 'CV2', 'CV3', 'CV4', 'CV5', 'CV6', 'CV7'],
    contact: {
      email: 'sarah@midlandelectrical.co.uk',
      phone: '024 7601 2345',
      website: 'https://midlandelectrical.co.uk',
      address: 'Canley, Coventry, CV4',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 52,
      averageRating: 4.8,
      jobsCompleted: 198,
      responseTimeHours: 4,
      memberSince: '2022-01-10',
    },
    pricing: {
      'consumer-unit': { priceFrom: 45000, priceTo: 80000, leadCost: 300 },
      'full-rewire': { priceFrom: 300000, priceTo: 700000, leadCost: 400 },
      'ev-charger': { priceFrom: 70000, priceTo: 120000, leadCost: 200 },
      'fault-finding': { priceFrom: 8000, priceTo: 20000, leadCost: 100 },
    },
    accountBalance: 3750,
  },
  {
    id: 'sup-003',
    slug: 'midland-build-solutions',
    companyName: 'Midland Build Solutions',
    ownerName: 'Dave Rowley',
    bio: 'Full-service building and construction company based in Nottingham. Over 20 years delivering extensions, loft conversions and commercial refurbishments across the East Midlands.',
    trades: ['builders'],
    coveragePostcodes: ['NG1', 'NG2', 'NG3', 'NG5', 'NG6', 'NG7', 'NG8', 'NG9'],
    contact: {
      email: 'dave@midlandbuild.co.uk',
      phone: '0115 901 2345',
      website: 'https://midlandbuild.co.uk',
      address: 'Beeston, Nottingham, NG9',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 31,
      averageRating: 4.7,
      jobsCompleted: 87,
      responseTimeHours: 8,
      memberSince: '2020-06-20',
    },
    pricing: {
      'extension': { priceFrom: 2000000, priceTo: 5000000, leadCost: 400 },
      'loft-conversion': { priceFrom: 3000000, priceTo: 6000000, leadCost: 400 },
      'garage-conversion': { priceFrom: 1000000, priceTo: 2500000, leadCost: 300 },
    },
    accountBalance: 8900,
  },
  {
    id: 'sup-004',
    slug: 'midland-surveying',
    companyName: 'Midland Surveying Ltd',
    ownerName: 'Helen Clarke',
    bio: 'RICS-regulated surveyors providing homebuyer reports, building surveys and valuations across Leicestershire and Northamptonshire. Fast turnaround, detailed reports.',
    trades: ['surveyors'],
    coveragePostcodes: ['LE1', 'LE2', 'LE3', 'LE4', 'LE5', 'NN1', 'NN2', 'NN3', 'NN4'],
    contact: {
      email: 'helen@midlandsurveying.co.uk',
      phone: '0116 201 2345',
      website: 'https://midlandsurveying.co.uk',
      address: 'Oadby, Leicester, LE2',
    },
    verification: 'featured',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 67,
      averageRating: 4.9,
      jobsCompleted: 245,
      responseTimeHours: 12,
      memberSince: '2019-11-01',
    },
    pricing: {
      'homebuyer-report': { priceFrom: 40000, priceTo: 80000, leadCost: 300 },
      'building-survey': { priceFrom: 60000, priceTo: 120000, leadCost: 400 },
      'valuation': { priceFrom: 25000, priceTo: 50000, leadCost: 200 },
    },
    accountBalance: 12300,
  },
  {
    id: 'sup-005',
    slug: 'apex-roofing-derby',
    companyName: 'Apex Roofing Derby',
    ownerName: 'Mark Foster',
    bio: 'Specialist roofing contractors serving Derby and Derbyshire. From emergency repairs to full re-roofs and flat roof systems. NFRC members with 18 years experience.',
    trades: ['roofers'],
    coveragePostcodes: ['DE1', 'DE3', 'DE21', 'DE22', 'DE23', 'DE24', 'DE13', 'DE14'],
    contact: {
      email: 'mark@apexroofingderby.co.uk',
      phone: '01332 901 234',
      website: 'https://apexroofingderby.co.uk',
      address: 'Allestree, Derby, DE22',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 43,
      averageRating: 4.6,
      jobsCompleted: 156,
      responseTimeHours: 6,
      memberSince: '2021-07-01',
    },
    pricing: {
      'roof-repair': { priceFrom: 30000, priceTo: 150000, leadCost: 200 },
      'full-reroof': { priceFrom: 500000, priceTo: 1500000, leadCost: 400 },
      'flat-roof': { priceFrom: 200000, priceTo: 800000, leadCost: 300 },
    },
    accountBalance: 2800,
  },
  {
    id: 'sup-006',
    slug: 'prestige-painters-wolverhampton',
    companyName: 'Prestige Painters & Decorators',
    ownerName: 'Tony Griffiths',
    bio: 'Award-winning decorating team based in Wolverhampton. Interior and exterior painting, wallpapering and commercial projects. Fully insured, colour consultations available.',
    trades: ['painters-decorators'],
    coveragePostcodes: ['WV1', 'WV2', 'WV3', 'WV4', 'WV6', 'WV10', 'DY1', 'DY2'],
    contact: {
      email: 'tony@prestigepainters.co.uk',
      phone: '01902 901 234',
      website: 'https://prestigepainters.co.uk',
      address: 'Penn, Wolverhampton, WV4',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 58,
      averageRating: 4.8,
      jobsCompleted: 203,
      responseTimeHours: 3,
      memberSince: '2020-09-14',
    },
    pricing: {
      'interior-painting': { priceFrom: 80000, priceTo: 300000, leadCost: 100 },
      'exterior-painting': { priceFrom: 150000, priceTo: 500000, leadCost: 200 },
      'wallpapering': { priceFrom: 50000, priceTo: 200000, leadCost: 100 },
    },
    accountBalance: 6100,
  },
  {
    id: 'sup-007',
    slug: 'midlands-gas-engineers',
    companyName: 'Midlands Gas Engineers',
    ownerName: 'Colin Bowen',
    bio: 'Gas Safe registered engineers covering Burton upon Trent and South Derbyshire. Boiler servicing, gas safety checks and central heating repairs for landlords and homeowners.',
    trades: ['gas-engineers', 'plumbers'],
    coveragePostcodes: ['DE13', 'DE14', 'DE15', 'B70', 'B71', 'WS1', 'WS2'],
    contact: {
      email: 'colin@midlandsgasengineers.co.uk',
      phone: '01283 901 234',
      address: 'Horninglow, Burton upon Trent, DE14',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 29,
      averageRating: 4.7,
      jobsCompleted: 118,
      responseTimeHours: 5,
      memberSince: '2022-04-22',
    },
    pricing: {
      'gas-safety-check': { priceFrom: 6000, priceTo: 10000, leadCost: 50 },
      'boiler-service': { priceFrom: 7500, priceTo: 12000, leadCost: 200 },
      'boiler-repair': { priceFrom: 15000, priceTo: 50000, leadCost: 200 },
    },
    accountBalance: 4200,
  },
  {
    id: 'sup-008',
    slug: 'smooth-finish-plastering',
    companyName: 'Smooth Finish Plastering',
    ownerName: 'Ryan Sutton',
    bio: 'Experienced plasterers and drylining specialists operating across Northampton and Northamptonshire. Domestic and light commercial projects. Clean, punctual, highly rated.',
    trades: ['plasterers'],
    coveragePostcodes: ['NN1', 'NN2', 'NN3', 'NN4', 'NN5', 'NN6'],
    contact: {
      email: 'ryan@smoothfinish.co.uk',
      phone: '01604 901 234',
      address: 'Kingsthorpe, Northampton, NN2',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 37,
      averageRating: 4.8,
      jobsCompleted: 142,
      responseTimeHours: 4,
      memberSince: '2021-10-05',
    },
    pricing: {
      'room-plaster': { priceFrom: 30000, priceTo: 80000, leadCost: 100 },
      'full-house-plaster': { priceFrom: 300000, priceTo: 700000, leadCost: 300 },
      'skim-coat': { priceFrom: 15000, priceTo: 40000, leadCost: 50 },
    },
    accountBalance: 3300,
  },
];

export function getSupplierBySlug(slug: string): SupplierProfile | undefined {
  return MOCK_SUPPLIERS.find(s => s.slug === slug);
}

export function getReviewsForSupplier(supplierId: string): SupplierReview[] {
  return MOCK_REVIEWS.filter(r => r.supplierId === supplierId);
}

const MOCK_REVIEWS: SupplierReview[] = [
  {
    id: 'rev-001',
    supplierId: 'sup-001',
    customerName: 'Karen B.',
    rating: 5,
    comment: 'Absolutely brilliant service. James arrived within 2 hours, sorted our boiler issue and charged a fair price. Would not hesitate to recommend.',
    date: '2024-11-12',
    serviceType: 'Boiler Repair',
    location: 'Birmingham B15',
    verified: true,
  },
  {
    id: 'rev-002',
    supplierId: 'sup-001',
    customerName: 'Paul M.',
    rating: 5,
    comment: 'Used Swift for a full bathroom refit. Brilliant team, tidy work, finished on time and on budget. Very happy.',
    date: '2024-10-03',
    serviceType: 'Bathroom Refit',
    location: 'Edgbaston, B16',
    verified: true,
  },
  {
    id: 'rev-003',
    supplierId: 'sup-002',
    customerName: 'Lisa H.',
    rating: 5,
    comment: 'Professional, punctual and great value. Sarah\'s team rewired my whole house with minimal disruption. Highly recommended.',
    date: '2024-09-22',
    serviceType: 'Full Rewire',
    location: 'Coventry CV3',
    verified: true,
  },
  {
    id: 'rev-004',
    supplierId: 'sup-002',
    customerName: 'Rob W.',
    rating: 4,
    comment: 'Installed our EV charger quickly and cleanly. Minor scheduling delay but overall a great service.',
    date: '2024-08-14',
    serviceType: 'EV Charger Installation',
    location: 'Coventry CV5',
    verified: true,
  },
  {
    id: 'rev-005',
    supplierId: 'sup-004',
    customerName: 'Anita G.',
    rating: 5,
    comment: 'Helen provided a thorough homebuyer report that highlighted several issues I would have missed. Saved me from a costly mistake.',
    date: '2024-12-01',
    serviceType: 'Homebuyer Report',
    location: 'Leicester LE3',
    verified: true,
  },
  {
    id: 'rev-006',
    supplierId: 'sup-004',
    customerName: 'Michael T.',
    rating: 5,
    comment: 'Excellent building survey, very detailed and clearly explained. Fast turnaround too. Will use again.',
    date: '2024-11-05',
    serviceType: 'Building Survey',
    location: 'Northampton NN2',
    verified: true,
  },
];
