import type { SupplierProfile, SupplierReview } from '@/types';

export const MOCK_SUPPLIERS: SupplierProfile[] = [
  {
    id: 'sup-001',
    slug: 'swift-plumbing-london',
    companyName: 'Swift Plumbing & Heating',
    ownerName: 'James Thornton',
    bio: 'Family-run plumbing and heating business serving South and Central London for over 15 years. Gas Safe registered, fully insured. Specialising in boiler installations, bathroom refits and emergency call-outs.',
    trades: ['plumbers', 'gas-engineers'],
    coveragePostcodes: ['SW1', 'SW3', 'SW6', 'SE1', 'SE5', 'W1', 'W2'],
    contact: {
      email: 'james@swiftplumbing.co.uk',
      phone: '07700 900123',
      website: 'https://swiftplumbing.co.uk',
      address: 'Battersea, London, SW11',
    },
    verification: 'featured',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 84,
      averageRating: 4.9,
      jobsCompleted: 312,
      responseTimeHours: 2,
      memberSince: '2021-03-15',
    },
    pricing: {
      'boiler-service': { priceFrom: 7500, priceTo: 12000, leadCost: 200 },
      'boiler-installation': { priceFrom: 200000, priceTo: 350000, leadCost: 300 },
      'emergency-leak': { priceFrom: 15000, priceTo: 30000, leadCost: 250 },
      'bathroom-installation': { priceFrom: 300000, priceTo: 800000, leadCost: 300 },
    },
    accountBalance: 12500,
  },
  {
    id: 'sup-002',
    slug: 'capital-electrical-services',
    companyName: 'Capital Electrical Services',
    ownerName: 'Sarah Okafor',
    bio: 'NICEIC-approved electrical contractor covering North and East London. All work certified and Part P compliant. From single socket to full rewires, we provide professional, clean and reliable service.',
    trades: ['electricians'],
    coveragePostcodes: ['N1', 'N2', 'E1', 'E2', 'E3', 'EC1', 'EC2'],
    contact: {
      email: 'sarah@capitalelectrical.co.uk',
      phone: '07700 900456',
      address: 'Islington, London, N1',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 67,
      averageRating: 4.8,
      jobsCompleted: 245,
      responseTimeHours: 4,
      memberSince: '2020-09-01',
    },
    pricing: {
      'full-rewire': { priceFrom: 350000, priceTo: 600000, leadCost: 400 },
      'fuse-box': { priceFrom: 60000, priceTo: 120000, leadCost: 350 },
      'socket-installation': { priceFrom: 8000, priceTo: 15000, leadCost: 150 },
      'ev-charger': { priceFrom: 80000, priceTo: 130000, leadCost: 300 },
    },
    accountBalance: 8750,
  },
  {
    id: 'sup-003',
    slug: 'northern-build-solutions',
    companyName: 'Northern Build Solutions',
    ownerName: 'Dave Whitfield',
    bio: 'Manchester-based building company specialising in house extensions, loft conversions and structural alterations. 20+ years experience. All trades in-house. Fully project managed from planning to completion.',
    trades: ['builders'],
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M14', 'M15', 'M16', 'M20', 'M21'],
    contact: {
      email: 'dave@northernbuild.co.uk',
      phone: '07700 900789',
      website: 'https://northernbuild.co.uk',
      address: 'Didsbury, Manchester, M20',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 42,
      averageRating: 4.7,
      jobsCompleted: 89,
      responseTimeHours: 12,
      memberSince: '2022-01-10',
    },
    pricing: {
      'house-extension': { priceFrom: 3000000, priceTo: 8000000, leadCost: 400 },
      'loft-conversion': { priceFrom: 2500000, priceTo: 6000000, leadCost: 400 },
      'garage-conversion': { priceFrom: 800000, priceTo: 2000000, leadCost: 350 },
    },
    accountBalance: 5000,
  },
  {
    id: 'sup-004',
    slug: 'midland-surveys-ltd',
    companyName: 'Midland Surveys Ltd',
    ownerName: 'Helen Cartwright',
    bio: 'RICS Chartered Surveyors serving the West Midlands and surrounding areas. Homebuyer reports, full building surveys, valuations and party wall matters. Turnaround typically 3–5 working days.',
    trades: ['surveyors'],
    coveragePostcodes: ['B1', 'B2', 'B3', 'B4', 'B5', 'B6', 'B11', 'B12', 'B13', 'B14', 'B15'],
    contact: {
      email: 'helen@midlandsurveys.co.uk',
      phone: '07700 900321',
      website: 'https://midlandsurveys.co.uk',
      address: 'Edgbaston, Birmingham, B15',
    },
    verification: 'featured',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 103,
      averageRating: 4.9,
      jobsCompleted: 420,
      responseTimeHours: 6,
      memberSince: '2019-06-20',
    },
    pricing: {
      'homebuyer-report': { priceFrom: 35000, priceTo: 60000, leadCost: 250 },
      'building-survey': { priceFrom: 60000, priceTo: 120000, leadCost: 350 },
      'valuation': { priceFrom: 25000, priceTo: 45000, leadCost: 200 },
    },
    accountBalance: 22000,
  },
  {
    id: 'sup-005',
    slug: 'apex-roofing-bristol',
    companyName: 'Apex Roofing Bristol',
    ownerName: 'Mark Jenkins',
    bio: 'Bristol-based roofing company with 18 years experience. Specialising in tiled roofs, flat roofs, GRP fibreglass, guttering and chimney repairs. Free written quotations. 10-year workmanship guarantee on all re-roofs.',
    trades: ['roofers'],
    coveragePostcodes: ['BS1', 'BS2', 'BS3', 'BS4', 'BS5', 'BS6', 'BS7', 'BS8', 'BS9', 'BS10'],
    contact: {
      email: 'mark@apexroofing.co.uk',
      phone: '07700 900654',
      address: 'Clifton, Bristol, BS8',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 58,
      averageRating: 4.6,
      jobsCompleted: 198,
      responseTimeHours: 8,
      memberSince: '2021-08-05',
    },
    pricing: {
      'tile-replacement': { priceFrom: 20000, priceTo: 60000, leadCost: 150 },
      'full-reroof': { priceFrom: 400000, priceTo: 1200000, leadCost: 300 },
      'flat-roof-repair': { priceFrom: 50000, priceTo: 200000, leadCost: 200 },
      'guttering': { priceFrom: 30000, priceTo: 80000, leadCost: 150 },
    },
    accountBalance: 3500,
  },
  {
    id: 'sup-006',
    slug: 'prestige-painters-london',
    companyName: 'Prestige Painters & Decorators',
    ownerName: 'Tony Bellini',
    bio: 'Professional painting and decorating across West and South West London. Interior and exterior. High quality finishes, minimal disruption. Colour consultations available. Fully insured, references on request.',
    trades: ['painters-decorators'],
    coveragePostcodes: ['SW1', 'SW3', 'SW6', 'W1', 'W2', 'W6', 'NW1'],
    contact: {
      email: 'tony@prestigepainters.co.uk',
      phone: '07700 900987',
      address: 'Chelsea, London, SW3',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: false,
    stats: {
      reviewCount: 31,
      averageRating: 4.8,
      jobsCompleted: 115,
      responseTimeHours: 24,
      memberSince: '2023-02-14',
    },
    pricing: {
      'interior-painting': { priceFrom: 80000, priceTo: 300000, leadCost: 150 },
      'exterior-painting': { priceFrom: 150000, priceTo: 500000, leadCost: 200 },
      'wallpapering': { priceFrom: 60000, priceTo: 180000, leadCost: 150 },
    },
    accountBalance: 1250,
  },
  {
    id: 'sup-007',
    slug: 'yorkshire-gas-services',
    companyName: 'Yorkshire Gas Services',
    ownerName: 'Colin Bradshaw',
    bio: 'Gas Safe registered engineer covering Leeds and surrounding areas. Boiler installations, servicing, breakdowns and landlord gas safety certificates. Emergency call-outs 7 days a week.',
    trades: ['gas-engineers', 'plumbers'],
    coveragePostcodes: ['LS1', 'LS2', 'LS3', 'LS4', 'LS6', 'LS7', 'LS8', 'LS11', 'LS12'],
    contact: {
      email: 'colin@yorkshiregas.co.uk',
      phone: '07700 900111',
      address: 'Headingley, Leeds, LS6',
    },
    verification: 'verified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 77,
      averageRating: 4.7,
      jobsCompleted: 289,
      responseTimeHours: 3,
      memberSince: '2020-11-30',
    },
    pricing: {
      'boiler-service': { priceFrom: 7000, priceTo: 11000, leadCost: 175 },
      'boiler-installation': { priceFrom: 200000, priceTo: 300000, leadCost: 300 },
      'gas-safety-cert': { priceFrom: 5000, priceTo: 8000, leadCost: 150 },
    },
    accountBalance: 9800,
  },
  {
    id: 'sup-008',
    slug: 'smooth-finish-plastering',
    companyName: 'Smooth Finish Plastering',
    ownerName: 'Ryan O\'Sullivan',
    bio: 'Skilled plasterer based in Manchester covering Greater Manchester area. Skim coating, full re-plasters, dot and dab and artex removal. Clean and tidy worker. Free quotes provided.',
    trades: ['plasterers'],
    coveragePostcodes: ['M1', 'M2', 'M3', 'M4', 'M8', 'M11', 'M12', 'M13', 'M14'],
    contact: {
      email: 'ryan@smoothfinish.co.uk',
      phone: '07700 900222',
      address: 'Chorlton, Manchester, M21',
    },
    verification: 'unverified',
    status: 'active',
    leadsEnabled: true,
    stats: {
      reviewCount: 19,
      averageRating: 4.5,
      jobsCompleted: 63,
      responseTimeHours: 12,
      memberSince: '2023-07-01',
    },
    pricing: {
      'skim-coat': { priceFrom: 15000, priceTo: 40000, leadCost: 100 },
      'full-replaster': { priceFrom: 80000, priceTo: 250000, leadCost: 150 },
      'artex-removal': { priceFrom: 20000, priceTo: 60000, leadCost: 100 },
    },
    accountBalance: 750,
  },
];

export const MOCK_REVIEWS: SupplierReview[] = [
  {
    id: 'rev-001',
    supplierId: 'sup-001',
    customerName: 'Sophie H.',
    rating: 5,
    comment: 'James was fantastic — arrived within an hour of my call for an emergency leak and fixed everything quickly and professionally. Great value too. Highly recommend.',
    serviceType: 'Emergency leak repair',
    location: 'Clapham, London',
    date: '2025-11-18',
    verified: true,
  },
  {
    id: 'rev-002',
    supplierId: 'sup-001',
    customerName: 'Michael T.',
    rating: 5,
    comment: 'Had a new combi boiler installed. James gave a clear quote, turned up on time and the job was done in a day. Tidy, efficient and competitively priced. Will use again.',
    serviceType: 'Boiler installation',
    location: 'Battersea, London',
    date: '2025-10-03',
    verified: true,
  },
  {
    id: 'rev-003',
    supplierId: 'sup-002',
    customerName: 'Amelia F.',
    rating: 5,
    comment: 'Sarah rewired our Victorian terrace over 3 days. She was professional, explained everything clearly and left the house spotless. NICEIC certificate provided. 10/10.',
    serviceType: 'Full rewire',
    location: 'Islington, London',
    date: '2025-09-14',
    verified: true,
  },
  {
    id: 'rev-004',
    supplierId: 'sup-002',
    customerName: 'Raj P.',
    rating: 4,
    comment: 'Good electrician, fitted 3 new sockets and sorted a faulty light. Arrived on time and did clean work. Slightly expensive but reliable.',
    serviceType: 'Socket installation',
    location: 'Hackney, London',
    date: '2025-08-22',
    verified: true,
  },
  {
    id: 'rev-005',
    supplierId: 'sup-003',
    customerName: 'Claire B.',
    rating: 5,
    comment: 'Dave and his team built a large rear extension. From planning permission to handover took 5 months. Communication was excellent throughout and the quality is superb.',
    serviceType: 'House extension',
    location: 'Didsbury, Manchester',
    date: '2025-11-01',
    verified: true,
  },
  {
    id: 'rev-006',
    supplierId: 'sup-004',
    customerName: 'Gareth W.',
    rating: 5,
    comment: 'Helen provided a thorough homebuyer report that highlighted issues the estate agent glossed over. It saved us from a very costly mistake. Worth every penny.',
    serviceType: 'Homebuyer report',
    location: 'Edgbaston, Birmingham',
    date: '2025-10-25',
    verified: true,
  },
  {
    id: 'rev-007',
    supplierId: 'sup-005',
    customerName: 'Natalie C.',
    rating: 4,
    comment: 'Mark and team did a great job on our re-roof. Took 4 days, cleaned up after themselves. Slight communication issue at the start but the end result is excellent.',
    serviceType: 'Full re-roof',
    location: 'Clifton, Bristol',
    date: '2025-07-12',
    verified: true,
  },
  {
    id: 'rev-008',
    supplierId: 'sup-007',
    customerName: 'Paul D.',
    rating: 5,
    comment: 'Boiler broke on a Saturday evening. Colin was there by 9am Sunday and had it fixed within 2 hours. Fair price for emergency call-out. Very impressed.',
    serviceType: 'Boiler repair',
    location: 'Headingley, Leeds',
    date: '2025-12-05',
    verified: true,
  },
];

export function getSupplierBySlug(slug: string): SupplierProfile | undefined {
  return MOCK_SUPPLIERS.find(s => s.slug === slug);
}

export function getSuppliersByTrade(tradeSlug: string): SupplierProfile[] {
  return MOCK_SUPPLIERS.filter(s => s.trades.includes(tradeSlug as any) && s.status === 'active' && s.leadsEnabled);
}

export function getSuppliersByPostcode(postcode: string): SupplierProfile[] {
  const district = postcode.trim().toUpperCase().replace(/\s+/g, '').slice(0, -3);
  return MOCK_SUPPLIERS.filter(s =>
    s.status === 'active' &&
    s.leadsEnabled &&
    s.coveragePostcodes.some(p => district.startsWith(p) || p.startsWith(district))
  );
}

export function getReviewsForSupplier(supplierId: string): SupplierReview[] {
  return MOCK_REVIEWS.filter(r => r.supplierId === supplierId);
}
