import type { TradeCategory, TradeSlug } from '@/types';

export const TRADE_CATEGORIES: TradeCategory[] = [
  {
    slug: 'plumbers',
    name: 'Plumbers',
    singularName: 'Plumber',
    icon: '🔧',
    description: 'From emergency leaks to full bathroom installations, find trusted local plumbers near you.',
    averageCostFrom: 5000,
    averageCostTo: 150000,
    leadPriceFrom: 100,
    leadPriceTo: 300,
    popularLocations: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Bristol'],
    commonServices: ['Emergency leak repair', 'Boiler service', 'Bathroom installation', 'Pipe replacement', 'Radiator fitting'],
  },
  {
    slug: 'electricians',
    name: 'Electricians',
    singularName: 'Electrician',
    icon: '⚡',
    description: 'Certified electricians for rewiring, fuse boxes, sockets, lighting and more.',
    averageCostFrom: 5000,
    averageCostTo: 500000,
    leadPriceFrom: 150,
    leadPriceTo: 400,
    popularLocations: ['London', 'Manchester', 'Birmingham', 'Edinburgh', 'Bristol'],
    commonServices: ['Full rewire', 'Fuse box replacement', 'Socket installation', 'Outdoor lighting', 'EV charger installation'],
  },
  {
    slug: 'builders',
    name: 'Builders',
    singularName: 'Builder',
    icon: '🏗️',
    description: 'Extensions, loft conversions, structural work — connect with reliable local builders.',
    averageCostFrom: 100000,
    averageCostTo: 20000000,
    leadPriceFrom: 200,
    leadPriceTo: 400,
    popularLocations: ['London', 'Manchester', 'Leeds', 'Bristol', 'Sheffield'],
    commonServices: ['House extension', 'Loft conversion', 'New build', 'Structural repairs', 'Garage conversion'],
  },
  {
    slug: 'surveyors',
    name: 'Surveyors',
    singularName: 'Surveyor',
    icon: '📐',
    description: 'RICS-accredited surveyors for homebuyer reports, building surveys and valuations.',
    averageCostFrom: 30000,
    averageCostTo: 200000,
    leadPriceFrom: 150,
    leadPriceTo: 350,
    popularLocations: ['London', 'Manchester', 'Birmingham', 'Bristol', 'Leeds'],
    commonServices: ['Homebuyer report', 'Building survey', 'Valuation report', 'Snagging survey', 'Party wall survey'],
  },
  {
    slug: 'gas-engineers',
    name: 'Gas Engineers',
    singularName: 'Gas Engineer',
    icon: '🔥',
    description: 'Gas Safe registered engineers for boiler installation, repairs and gas safety checks.',
    averageCostFrom: 5000,
    averageCostTo: 400000,
    leadPriceFrom: 100,
    leadPriceTo: 300,
    popularLocations: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Newcastle'],
    commonServices: ['Boiler installation', 'Boiler repair', 'Gas safety certificate', 'Central heating service', 'Landlord gas check'],
  },
  {
    slug: 'roofers',
    name: 'Roofers',
    singularName: 'Roofer',
    icon: '🏠',
    description: 'Roof repairs, replacement, guttering and lead flashing from vetted local roofers.',
    averageCostFrom: 20000,
    averageCostTo: 1500000,
    leadPriceFrom: 100,
    leadPriceTo: 300,
    popularLocations: ['London', 'Manchester', 'Birmingham', 'Liverpool', 'Bristol'],
    commonServices: ['Tile replacement', 'Full re-roof', 'Guttering', 'Flat roof repair', 'Chimney repair'],
  },
  {
    slug: 'plasterers',
    name: 'Plasterers',
    singularName: 'Plasterer',
    icon: '🪣',
    description: 'Skim coating, dot and dab, dry lining and artex removal from local plasterers.',
    averageCostFrom: 15000,
    averageCostTo: 600000,
    leadPriceFrom: 75,
    leadPriceTo: 200,
    popularLocations: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Bristol'],
    commonServices: ['Skim coat', 'Full re-plaster', 'Dry lining', 'Artex removal', 'Coving installation'],
  },
  {
    slug: 'painters-decorators',
    name: 'Painters & Decorators',
    singularName: 'Painter & Decorator',
    icon: '🎨',
    description: 'Interior and exterior painting, wallpapering and decorating services near you.',
    averageCostFrom: 20000,
    averageCostTo: 800000,
    leadPriceFrom: 75,
    leadPriceTo: 200,
    popularLocations: ['London', 'Manchester', 'Birmingham', 'Bristol', 'Leeds'],
    commonServices: ['Interior painting', 'Exterior painting', 'Wallpapering', 'Feature walls', 'Commercial decoration'],
  },
  {
    slug: 'joiners-carpenters',
    name: 'Joiners & Carpenters',
    singularName: 'Joiner & Carpenter',
    icon: '🪚',
    description: 'Bespoke joinery, fitted wardrobes, doors, staircases and timber work.',
    averageCostFrom: 20000,
    averageCostTo: 1000000,
    leadPriceFrom: 100,
    leadPriceTo: 250,
    popularLocations: ['London', 'Manchester', 'Leeds', 'Bristol', 'Edinburgh'],
    commonServices: ['Fitted wardrobes', 'Staircase replacement', 'Door fitting', 'Skirting boards', 'Loft boarding'],
  },
  {
    slug: 'tilers',
    name: 'Tilers',
    singularName: 'Tiler',
    icon: '🟦',
    description: 'Wall and floor tiling for bathrooms, kitchens and more from skilled local tilers.',
    averageCostFrom: 30000,
    averageCostTo: 400000,
    leadPriceFrom: 75,
    leadPriceTo: 200,
    popularLocations: ['London', 'Manchester', 'Birmingham', 'Leeds', 'Bristol'],
    commonServices: ['Bathroom tiling', 'Kitchen splashback', 'Floor tiling', 'Wet room', 'Outdoor paving'],
  },
];

export const TRADE_SLUGS: TradeSlug[] = TRADE_CATEGORIES.map(t => t.slug);

export function getTradeBySlug(slug: string): TradeCategory | undefined {
  return TRADE_CATEGORIES.find(t => t.slug === slug);
}
